### ISSUE TITLE
Expression Model

### ISSUE THREAD

**Issue by John-Yao** [deepmo24/CPEM#3]
Hi, I'm curious about how to 'mean_delta_blendshape.npy'!

Could you release more detail or source code about it?

Thanks!

**Comment by deepmo24** [comment]
Hi, we use [deformation transfer](https://people.csail.mit.edu/sumner/research/deftransfer/Sumner2004DTF.pdf) to  transfer the expression blendshapes from FaceWarehouse to the mean shape(B_0) of BFM09, so that we can get blendshape {B_i} in BFM09 topology,  while i \in 1...46. Then we get the delta blendshapes by calculating \delta_B_i =  B_i - B_0, which is saved in  'mean_delta_blendshape.npy'.

**Comment by John-Yao** [comment]
Thanks for your reply! 

Which  repo of deformation transfer do you use? 

We try these [repo](https://github.com/mickare/Deformation-Transfer-for-Triangle-Meshes). But the mouth seem could not open.

I am curious about Why do not using FaceWarehouse directly .

**Comment by deepmo24** [comment]
1. We adapt the code from [this repo](https://github.com/SuwoongHeo/Deformation-Transfer-Matlab). 
2. FaceWarehouse doesn't have the texture model. For self-supervised training, we transfer the expression blendshape to BFM09, which has both texture and shape models.

**Comment by John-Yao** [comment]
Thanks for your reply!
